accelerator: gpu
accum_grads: 1
batch_frames: 64
batch_pixels: 2048
consecutive_train: false
data_name: cylinder
dec_num_cross_attention_heads: 1
dec_num_latent_channels: 16
dec_preproc_ch: 16
dropout: 0.0
enc_num_latent_channels: 16
enc_num_self_attention_heads: 2
enc_preproc_ch: 32
gpu_device:
- 0
im_ch: 1
image_size:
- 112
- 192
latent_size: 1
load_model_num: null
lr: 0.0001
num_batches: 8
num_cross_attention_heads: 2
num_latents: 256
num_layers: 3
num_self_attention_layers_per_block: 3
num_sensors: 8
seed: 123
space_bands: 32
test: false
total_frames: 5000
training_frames: 50
