accelerator: gpu
accum_grads: null
batch_frames: 16
batch_pixels: 1024
consecutive_train: false
data_name: fire
dec_num_cross_attention_heads: 1
dec_num_latent_channels: 32
dec_preproc_ch: 32
dropout: 0.0
enc_num_latent_channels: 32
enc_num_self_attention_heads: 2
enc_preproc_ch: 32
gpu_device:
- 0
im_ch: 1
image_size:
- 31
- 11
- 16
- 1
latent_size: 1
load_model_num: null
lr: 0.0001
num_batches: 133
num_cross_attention_heads: 2
num_latents: 512
num_layers: 3
num_self_attention_layers_per_block: 3
num_sensors: 12
seed: null
space_bands: 6
test: false
total_frames: 600
training_frames: 400
